version: "3"
services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/sockets && bundle exec puma -C config/puma.rb"
    volumes:
      - ./back:/app
      - public:/app/public
      - tmp:/app/tmp
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    networks:
      - mynetwork

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
      - ./back:/app  # Railsアプリケーションのコードをnginxコンテナにマウント
    ports:
      - "80:80"
    depends_on:
      - back
      - front
    networks:
      - mynetwork

volumes:
  postgres_data:
  tmp:
  public:

networks:
  mynetwork:
    driver: bridge


