default: &default
  adapter: postgresql
  encoding: unicode
  username: user
  password: password
  host: db
  port: 5432
  database: app_development

development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV["APP_DATABASE"] %>
  username: <%= ENV["APP_DATABASE_USERNAME"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  host: <%= ENV["APP_DATABASE_HOST"] %>  ##デプロイ先の環境変数に渡してあげると接続されるはず

